### PR TITLE
make it compile again & work on stable rust

### PR DESCRIPTION
**Pull request by superwhiskers**
this removes all unstable feature usage from the repository and makes it compile on the latest stable version

### CODE REVIEW

**Review by Fuwn — CHANGES_REQUESTED** [review]
I'm not really in favour of removing a couple of standard configuration files only to replace them with more environment-specific configuration files, which most users can't even make use of, especially for a project as small as this one.

I'm not too fond of removing `Cargo.toml` documentation either just for the sake of conciseness.

I'd be fine with pinning the toolchain and dropping the unstable requirements, given that viable replacements can be found. The replacements that were implemented in this PR make the source unreadable and unrecognisable compared to the original implementation.

Reformatting the whole project in one go alongside completely rewriting the implementation in one commit doesn't seem sound either.

**Comment by superwhiskers** [comment]
there's no real source rewrite here, i just dropped the entire rustfmt.toml file since it seemed (?) that a chunk of the configuration options in there relied on unstable features

**Comment by Fuwn** [comment]
It might just be easier to replace the configuration with an up-to-date one then, like [Fuwn/Koi/rustfmt.toml](https://github.com/Fuwn/Koi/blob/master/rustfmt.toml).

I'd consider `ppm.rs` rewritten. Comparing it to the original implementation linked in the README, nearly all line-by-line similarity is gone. For instance, `read_line_types` doesn't even exist any more in this PR.

**Comment by superwhiskers** [comment]
there. i made a commit which brought the formatting back in line with what you had before so the diff should be easier to read now

**Comment by superwhiskers** [comment]
let me know if you also want me to add makefile.toml back

**Review by Fuwn — CHANGES_REQUESTED** [review]
https://github.com/Fuwn/para/pull/2#issuecomment-1965857879

**Comment by superwhiskers** [comment]
i've taken your up to date formatting configuration and pruned everything that needs unstable rustfmt features

**Comment by superwhiskers** [comment]
i'll squash the changes one more time

**Review by Fuwn — CHANGES_REQUESTED** [review]
I'm not sure the EditorConfig file is needed, since the `rustfmt.toml` exists. From my experience, most editors tend to respect the `rustfmt.toml` file and treat it similarly to an EditorConfig anyway.

`debug = false` seems to be default for the `release` profile, so this isn't necessary to explicitly define this. `panic = "abort"` seems fine, but it makes it difficult to debug any errors in `release`. It should be OK for now, though.

I wouldn't unpin dependencies in `Cargo.toml`, even if adding `Cargo.lock` back.

Once again, the structure of `ppm.rs` has been completely altered, leaving it unrecognisable from the original implementation.

Deleting the cargo-make file isn't necessary, either. `rustfmt.toml` may depend on nightly Rust, but that doesn't mean the source has to. The cargo-make rules make sure of that. Although, in our case, nightly is still required due to access various nightly features such as generators.

The only valid changes I'd approve at this point are updating the `rustfmt.toml` and `rust-toolchain` files, adding the lock-file back, and tampering with the `release` profile.

Unless a minimally invasive dependency or changes can be added without getting rid of the generator, there is no point in changing the implementation, leaving it vastly different from the original.

Once again, this project isn't necessary a throw-it-all-out-and-rewrite-it-in-Rust-from-scratch, but rather an educational and faithful re-implementation.

**Comment by superwhiskers** [comment]
> I'm not sure the EditorConfig file is needed, since the rustfmt.toml exists. From my experience, most editors tend to respect the rustfmt.toml file and treat it similarly to an EditorConfig anyway.

the editor i used to make these changes doesn't respect `rustfmt.toml`, so i added it for the purposes of being able to work on this codebase

> debug = false seems to be default for the release profile, so this isn't necessary to explicitly define this. panic = "abort" seems fine, but it makes it difficult to debug any errors in release. It should be OK for now, though.

both of these i just blindly copied over from another rust project of mine as i was compiling your project for performance comparison purposes

> I wouldn't unpin dependencies in Cargo.toml, even if adding Cargo.lock back.

they weren't pinned to begin with. if i recall correctly, the way versions are checked by cargo mean that the way i tweaked them to be specified is basically how cargo treats them internally. i only changed this for clarity's sake

> Once again, the structure of ppm.rs has been completely altered, leaving it unrecognisable from the original implementation.
> ...
> Although, in our case, nightly is still required due to access various nightly features such as generators.

i apologize for not making this clear from the beginning, but i've already removed all of the nightly feature usage here. that's all i've meaningfully done to your source code. all of the other changes i submitted initially were just other things i did in the process of cleaning up the source code to make it work on stable rust. there weren't any other changes made to the source besides that and addressing clippy lints that came up since i wanted to polish it as much as possible prior to submission

> Deleting the cargo-make file isn't necessary, either. rustfmt.toml may depend on nightly Rust, but that doesn't mean the source has to. The cargo-make rules make sure of that.

i'll add this back

**Comment by Fuwn** [comment]
Sure. I understand that it is equivalent, and I'm not doubting that, but again, this project is not a rewrite-it-in-Rust-from-scratch. It is an identical source-to-source equivalent. Like I said, the changes are unreadable compared to the original.

Have you benchmarked the current implementation v.s. the changes? If there is a meaningful difference, I might consider this change on a new branch. Until then, there is no point in mangling the source just to switch off of nightly with zero runtime improvements. When I was testing the changes, stable was actually significantly slower than nightly.

There are binary releases available, which most people have been utilising. Stable v.s. nightly is not meaningful to consumers. This is isn't a library.

**Pull request closed without merging**
